
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aoife Sayers
 */
public class frmUpload extends javax.swing.JFrame {
    
    private final JFileChooser fileChooser;

    /**
     * Creates new form fileChooser
     */
    public frmUpload() {
        initComponents();
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\FileManagementSystem\\DistributedComputingFileMgmtSystem\\"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("FileFilters", "jpg", "png", "gif", "txt", "html", "docs", "pdf"));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnUploadFile = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuLogin = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenu();
        mnuUpload = new javax.swing.JMenu();
        mnuDownload = new javax.swing.JMenu();
        mnuRegister = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Upload");

        btnUploadFile.setText("Upload File..");
        btnUploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(374, 374, 374))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnUploadFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadFile)
                    .addComponent(messageLabel))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        mnuLogin.setText("Login");
        mnuLogin.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuLoginMenuSelected(evt);
            }
        });
        mnuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuLogin);

        mnuLogout.setText("Logout");
        mnuLogout.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuLogoutMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuLogout);

        mnuUpload.setText("Upload");
        mnuUpload.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuUploadMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuUpload);

        mnuDownload.setText("Download");
        mnuDownload.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuDownloadMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuDownload);

        mnuRegister.setText("Register");
        mnuRegister.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuRegisterMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuRegister);

        mnuExit.setText("Exit");
        mnuExit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuExitMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFileActionPerformed
        // TODO add your handling code here:
        int returnValue = fileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            messageLabel.setText("File choosen!");
            String s = fileChooser.getSelectedFile().toPath().toString();
            JOptionPane.showMessageDialog(null, "You want to upload " + s);
            Path path = Paths.get(s);
            byte[] data;
            LoggedInUsers.AddToList(new User("AoifeSayers", "Hi"));
            try{
               data = Files.readAllBytes(path);
               String byteDataString = new String(data);
               String hostName = "localhost";
               String portNum = "7";
               ClientHelper helper = new ClientHelper(hostName, portNum);
               String username = JOptionPane.showInputDialog("Enter username");
               String fileName = JOptionPane.showInputDialog("Enter file name for the server");
               String serverResult = helper.send("3" + ", " +  username + ", " + fileName + ", " + byteDataString);
               JOptionPane.showMessageDialog(null, serverResult, "Server Result for upload", JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
            }catch(IOException ex){
               ex.printStackTrace();
            }
        }//end if
        else{
            messageLabel.setText("No file choosen!");
        }
    }//GEN-LAST:event_btnUploadFileActionPerformed

    private void mnuLoginMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuLoginMenuSelected
        this.setVisible(false);
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_mnuLoginMenuSelected

    private void mnuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginActionPerformed

    }//GEN-LAST:event_mnuLoginActionPerformed

    private void mnuLogoutMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuLogoutMenuSelected
        this.setVisible(false);
        frmLogout logout = new frmLogout();
        logout.setVisible(true);
    }//GEN-LAST:event_mnuLogoutMenuSelected

    private void mnuUploadMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuUploadMenuSelected
        this.setVisible(false);
        frmUpload upload = new frmUpload();
        upload.setVisible(true);
    }//GEN-LAST:event_mnuUploadMenuSelected

    private void mnuDownloadMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuDownloadMenuSelected
        this.setVisible(false);
        frmDownload download = new frmDownload();
        download.setVisible(true);
    }//GEN-LAST:event_mnuDownloadMenuSelected

    private void mnuRegisterMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuRegisterMenuSelected
        this.setVisible(false);
        frmRegister register = new frmRegister();
        register.setVisible(true);
    }//GEN-LAST:event_mnuRegisterMenuSelected

    private void mnuExitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuExitMenuSelected
        this.setVisible(false);
    }//GEN-LAST:event_mnuExitMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUpload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUploadFile;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JMenu mnuDownload;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenu mnuLogout;
    private javax.swing.JMenu mnuRegister;
    private javax.swing.JMenu mnuUpload;
    // End of variables declaration//GEN-END:variables
}
